package com.codapes.siswisp.entity;
// Generated 03/08/2016 04:56:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Cuentausuario generated by hbm2java
 */
@Entity
@Table(name = "CUENTA_USUARIO", schema = "SISWISP")
public class Cuentausuario implements java.io.Serializable {

    @Id
    @GeneratedValue
    private Integer id;
    
    
    @JoinColumn(name = "USUARIO_ID")
    @OneToOne(fetch = FetchType.LAZY)
    private Usuario usuario;
    
    @Column(name = "USUARIO")
    private String user;
    
    @Column(name = "PASSWORD")
    private String password;
    
    @Column(name = "VELOCIDAD")
    private String velocidad;
    
    @Column(name = "PAGO_MENSUAL")
    private long pagoMensual;
    
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    @Column(name = "FECHA_INICIO")
    @Temporal(TemporalType.DATE )
    private Date fechaInicio;

    public Cuentausuario() {
    }

    public Cuentausuario(Usuario usuario, String user, String password, String velocidad, long pagoMensual, Date fechaInicio) {
        this.usuario = usuario;
        this.user = user;
        this.password = password;
        this.velocidad = velocidad;
        this.pagoMensual = pagoMensual;
        this.fechaInicio = fechaInicio;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getVelocidad() {
        return this.velocidad;
    }

    public void setVelocidad(String velocidad) {
        this.velocidad = velocidad;
    }

    public long getPagoMensual() {
        return this.pagoMensual;
    }

    public void setPagoMensual(long pagoMensual) {
        this.pagoMensual = pagoMensual;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

}
